openapi: 3.0.3
info:
  title: Scibble API
  description: Documentation on API endpoints
  version: 0.0.1
servers:
  - url: https://localhost:5101/api
    description: Locally-running server
  - url: https://scribble.com/api
    description: Production server
paths:
  /login:
    post:
      description: User authentication
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
            encoding:
              password:
                allowReserved: true
      responses:
        200:
          description: User session JWT token
          content:
            text/plain:
              schema:
                type: string
        401:
          description: Invalid login error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /users:
    get:
      description: All users
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserModel'
        401:
          description: User is not authenticated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuthenticationRequest:
      type: object
      properties:
        login:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - login
        - password

    UserModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string

    ErrorResponse:
      properties:
        status:
          type: integer
        title:
          type: string
